# DigitalOcean Production Docker Compose
# This configuration is optimized for DigitalOcean App Platform deployment
version: '3.8'

services:
  # FastAPI Backend
  backend:
    build:
      context: ./sunrise-backend-fastapi
      dockerfile: Dockerfile.prod
    container_name: sunrise-backend-do
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ENVIRONMENT=production
      - PORT=8000
    ports:
      - "8000:8000"
    networks:
      - sunrise-network
    restart: unless-stopped
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --workers 2
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # React Frontend
  frontend:
    build:
      context: ./sunrise-school-frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL:-https://your-app-name.ondigitalocean.app/api/v1}
        - REACT_APP_SCHOOL_NAME=Sunrise National Public School
    container_name: sunrise-frontend-do
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - sunrise-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sunrise-network:
    driver: bridge
