# DigitalOcean App Platform Configuration
name: sunrise-school-management
region: blr1

services:
- name: backend
  source_dir: /sunrise-backend-fastapi
  github:
    repo: javedansari81/sunrise-school-management
    branch: main
    deploy_on_push: true
  build_command: pip install -r requirements.txt && pip install gunicorn
  run_command: gunicorn main:app -w 2 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8080
  environment_slug: python
  instance_count: 1
  instance_size_slug: basic-xxs
  http_port: 8080
  health_check:
    http_path: /health
  envs:
  - key: DATABASE_URL
    scope: RUN_TIME
    type: SECRET
  - key: SECRET_KEY
    scope: RUN_TIME
    type: SECRET
  - key: ENVIRONMENT
    scope: RUN_TIME
    value: production

- name: frontend
  type: STATIC_SITE
  source_dir: /sunrise-school-frontend
  github:
    repo: javedansari81/sunrise-school-management
    branch: main
    deploy_on_push: true
  build_command: npm ci && npm run build
  output_dir: /build
  environment_slug: node-js
  envs:
  - key: REACT_APP_API_URL
    scope: BUILD_TIME
    value: https://sunrise-school-management.ondigitalocean.app/api/v1
  - key: REACT_APP_SCHOOL_NAME
    scope: BUILD_TIME
    value: Sunrise National Public School
  routes:
  - path: /
  catchall_document: index.html

databases:
- name: sunrise-postgres
  engine: PG
  version: "15"
  size: db-s-1vcpu-1gb
  num_nodes: 1
